export const CREATE_QUESTIONS = "CREATE_QUESTIONS";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTION_SUCCESS = "GET_ALL_QUESTION_SUCCESS";
export const GET_ALL_QUESTION_FAIL = "GET_ALL_QUESTION_FAIL";

export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";

export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";